language: generic
sudo: required
dist: trusty
env:
  matrix:
  - ARCH=armv6
  - ARCH=x86
  global:
  - secure: Sfn7BkmMzT/89M/fIk9BXbeTDhWWhG8DygQd5BGUbfKpbMgBPRMf4BuWy0MpNsz6JHO04k58hPOxqSdhSFexp8ywhkfD0F1zmm15yjBazeC3Y2HPdvj5v62bSaC6gHALU0YPNtPYQ8Ug/ezj0P/atRA6ZMddPd5SHdiz4j2pi4Ka+tVSVbB4lujyF9vmbtPcBjuBNb/yNCCZ7x8aZiMgOSzGTCowZeusoYFiDv3wCHxOF/bdMKKdsp9kupddhbrZD4Pdp6PpGUtfCaQrjLznQ/34mwFMNGyB2iyfuahni4TWOIXntF5xePqwBL5eMS0pmWzz343S800pIyxQ8+j39XTF2GdZ2QGDISJtVdx3KzshemyVkrGyEdVekxynDE1CP8wy5PdHKxaJJZounxcNDOgDjiUo0JtO1FEnQwKLxNmvtQtor8NUxpwE3BtwNT/cvgr87h1Vaq20ZC8/mMMNobI1MV/aMNiejfb3CPdol0EAuh+PBY+dGohKGlKB01/kQ+tDTvS/rgqeiw0KCjdzllBvgNOio8ard3THqQiedtuJ5ErPCAmk/ruRtQ3rkyL1hsc72P6LpuxKV5zt/Anj7Mzg11Dmom6Fwol230SO0s+sdChHg6qAnq1GrMC6iydIpFAD5PcRh1+ALpc5MWVMjhSfN8lXgeukn+c/jGvIbGw=
  - secure: Pq9sLm59heVVGH6zOl5VcxIB4KJF0ZnHCgrTVWqIR9p1UUnkc/Uvc4HmHj95tDAhmXDRfbuXvICgMOBRvmRYS3Z59nyGTA/nb8LmiYCTW7pmreOebKC6fD2FCozPs7DJNPWiAFVQm32NI7m2Fw6vimcXTtb0/MoDs7f8icze5PpmQKzuBP6OPIyky/S//SraFlMq8OqGmC/7fszY2wZyMjpdISmmmasuCSbZTuKqqYa14CRepyMrGWPs051hGj8ZT3BOIHPWNJ6UF4xxth0pjns+t0rJspqdoadYqDuKOIjD/rOgzagVnKvox8FYfBqEkaWgd1vMpZ/21x6kfqWXk8f2jSxf2HueYdQfoh/pPWv0DdqFuexAAQO0ZyIORj6h0CcccOykrfxE2bWpEIo7m0ypTE5jD1afmAVYT7uYDTWAmuiiN6Q+eyJ+FnNEIbPOFrKRPTW/X94Jwp0QFORFM/jE6Og3RhMnUDLTnSEeWspckUDhhdF0+QsI+Kics00XQTNUbNfaiffJTJyn9cb23oYFN4OKNqwreEy3W9gibGqsnIMomRCaZ6Bcj/WNP5+q6kkRQXxFGn72pl8WUKBAVolrBnbk/5dDKYbyWWz9RhW5p536nrYaEnIyqkUAJ4LtNNere6qiUdMfKY4jK6cQfVQgrAh3JHWdM9tNNe57Rb4=
services:
- docker
branches:
  only:
  - master
  - develop
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
install: true
script:
- make mk-image ARCH=$ARCH
- make mk-deployment VERSION=$TRAVIS_TAG
deploy:
- provider: script
  script: make pushtohub USER=$DOCKER_USER PASS=$DOCKER_PASS ARCH=$ARCH TAG=$TRAVIS_BRANCH
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master|develop$"
- provider: script
  script: make pushtohub USER=$DOCKER_USER PASS=$DOCKER_PASS ARCH=$ARCH TAG=$TRAVIS_TAG
  on:
    tags: true
    all_branches: true
- provider: releases
  prerelease: true
  skip_cleanup: true
  file_glob: true
  file: "./*.zip"
  api_key:
    secure: ELLZ+ViC1ZyqxqUdH150sdlbHHjQZyxDjlCMuTIppN6dim52hK5rjd/pHXzGwDAS9nXTG0Nwa8yTUA7pSXnOEbQOlRQnUMFqTIBkie4dfqPkCXX/VmXMmcWe/92nOzT89CmbUBZRZKtj6FjsQCVdegMSqD5Cj8EewqKwSX3dJBwTJX5IbmAm7A2Bgy8vWUMujo4zVsgLcEGZ++88xLyWZksfkPGmLXLj+rB21L8qdN5u2JtY2skgP5bPA6Ockp5wtg3JRyUjzvVh8VPyhC9YTMQkEd8ReU74Sch+iDbrKhLlwdmgR9iNb5+NEBNDii1Uanepfq9uzuE+F1DC7BQHrTip7WRB0fYwjvqE/ljnit1HvSq/QE+p9k9eNTZlQi4d41aQFK4Z0WI3Gq+aKMAtWlRAisBF0QaVU+tVLMVHiquld6aXAAbNv8OT7n6h9NSV81i5G2jvc9hr+3YqZJIt3fZ2etoEkkO/JQdDvYUZKZ5IeUnE5+GlZyuqvTW10inMijj9tHXW7FMk2v3vXYsvCqi1fFF6UUFYM2DYCd9Sc3kk+alrg/hTbh8ryWg0CAB/BzTEtuOM/Q3iuApxNzYGAi0qJEnR+TOCkcnejRPoFyTTWKQTGiJ0OhlehnwxSARU5ENUPD6PSdhMNu/Dcnw9f6rslCdTXExiGalaOHOZIrA=
  on:
    tags: true
    all_branches: true

